/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unipe.cc.views;

import br.unipe.cc.controllers.VeiculoController;
import br.unipe.cc.exceptions.VeiculoExistenteException;
import br.unipe.cc.models.Veiculo;
import br.unipe.cc.persistencia.VeiculoDao;
import javax.swing.JOptionPane;

/**
 *
 * @author João Felipe
 */
public class telaCadastrarVeiculo extends javax.swing.JInternalFrame {

    

    /**
     * Creates new form telaCadastrarVeiculo
     */
    public telaCadastrarVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ReceberPlaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ReceberChassi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ReceberAno = new javax.swing.JTextField();
        SalvarVeiculos = new javax.swing.JButton();
        CancelarVeiculos = new javax.swing.JButton();
        ReceberEscuderia = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Veículos");

        jLabel1.setText("Escuderia");

        jLabel2.setText("Placa");

        ReceberPlaca.setToolTipText("Informe a placa do véiculo");
        ReceberPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceberPlacaActionPerformed(evt);
            }
        });

        jLabel3.setText("Chassi");

        ReceberChassi.setToolTipText("Informe o Chassi do carro");

        jLabel4.setText("Ano");

        ReceberAno.setToolTipText("Informe o ano de fabricação de veículo");

        SalvarVeiculos.setText("Salvar");
        SalvarVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarVeiculosActionPerformed(evt);
            }
        });

        CancelarVeiculos.setText("Cancelar");
        CancelarVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarVeiculosActionPerformed(evt);
            }
        });

        ReceberEscuderia.setToolTipText("Informe a marca do carro");
        ReceberEscuderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceberEscuderiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ReceberEscuderia)
                                .addGap(95, 95, 95))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(ReceberChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(ReceberPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(ReceberAno))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 251, Short.MAX_VALUE)
                        .addComponent(SalvarVeiculos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CancelarVeiculos)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReceberPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReceberEscuderia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReceberAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SalvarVeiculos)
                            .addComponent(CancelarVeiculos)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReceberChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReceberPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceberPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReceberPlacaActionPerformed

    private void CancelarVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarVeiculosActionPerformed
        // Cancelando tarefa de tela Veículo
        this.dispose();
        JOptionPane.showMessageDialog(null, "Operação cancelada");
    }//GEN-LAST:event_CancelarVeiculosActionPerformed

    private void SalvarVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarVeiculosActionPerformed
  // salvar na classe Veículo
        JOptionPane.showMessageDialog(null, "Dados salvos");
        
        String chassi = ReceberChassi.getText();
        String placa = ReceberChassi.getText();
        String ano = ReceberAno.getText();
        String escuderia = ReceberEscuderia.getText();
        
       
        // criar um obejeto veiculo
        VeiculoController.getInstance();
        
        // chamar controlador
        //VeiculoController controladorVeiculo = new VeiculoController(); // voltar a mecher
        
        
    }//GEN-LAST:event_SalvarVeiculosActionPerformed

    private void ReceberEscuderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceberEscuderiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReceberEscuderiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarVeiculos;
    private javax.swing.JTextField ReceberAno;
    private javax.swing.JTextField ReceberChassi;
    private javax.swing.JTextField ReceberEscuderia;
    private javax.swing.JTextField ReceberPlaca;
    private javax.swing.JButton SalvarVeiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
